# Generated by Django 3.2.12 on 2022-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_auto_20220218_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
