# Generated by Django 3.2.12 on 2022-02-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_post_url_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='url_video',
            new_name='video',
        ),
    ]
